os: linux
sudo: false
language: python
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
    env: TOXENV=py37-stable,py37-cov,cov-codecov,linting,formatting,typing
  - python: '3.6'
    env: TOXENV=py36-stable,py36-cov,cov-codecov
  - python: '3.5'
    env: TOXENV=py35-stable,py35-cov,cov-codecov
  - python: pypy3
    env: TOXENV=pypy3-stable,pypy3-cov,cov-codecov
  allow_failures:
  - python: '3.7'
    dist: xenial
    sudo: true
    env: TOXENV=py37-latest
  - python: '3.6'
    env: TOXENV=py36-latest
  - python: '3.5'
    env: TOXENV=py35-latest
  - python: pypy3
    env: TOXENV=pypy3-latest
  fast_finish: true
install:
- pip install tox
script:
- tox
cache:
- pip
branches:
  only:
  - /^.*master$/
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  on:
    python: '3.6'
    tags: true
  provider: pypi
  user: "sprigmaintainer"
  password:
    secure: nzX0cWiZ5/P3VzZMMMX8+PMCQQvz4ZsydFOiuYe7XoJKiZdHTRuICZFx2kUOQ1XhBhYCdvWPUbSC/CDfwCHSJBDXKp8r7PQMInPUkpq8jTtxmMP7j2nlS8RiP97NJWWnIaFroR1mp3PcsZ05gleFzs93wLnbrU+f5kwYMLF42CYM/Ct3NCUQqaWikDBC1732inux5zAiHl8bH5dKdvvYbaYAvAbgQgqGHZF45BeVogjbKy0qfcfmdAYjC+VAX9QmAzKUcW9nLpNQrUI8XynOAkqlr0u1xfM4NuGbe20xgfIpLKAM7fa08d2W+eBMpTO/wi0IG0GbKkHwDGe3Ttf/Mcgiad8cNwDsvPvWmZPfSQ7d9GHnPONaF1D5yEMs08zkbVs8qPK5DWJ5e7PaljIGQIlBqxfnOGZDHk4CPSdY1wKHypAM0/FIgA78gbxsJ6blv9T7O4E1l2Ec6+fTgZgSJl5EYXkKlh6Qq5SurPyIQWSwImeDxTUIzbhgX6+FgCvvWaMQHnGMo3dBtoCGfrN+2FeYqR8B/C8u5hLvAxbk/FeXPR64JpAezLJG900Y0CJAa3RBA1IkkUvPiEhfuHgnn4NJZnDqN8lJYGazJZQdjJIeASD2UtIo9vqINc29kq3E2YtxHPZn242oTBSOd7jONYWTQl2ApVIy6w5QBXjepC8=
